In [205]:
import numpy as np
import pandas as pd

In [206]:
df = pd.read_excel (r'C:\Users\wqc32\Downloads\360 Product Research Excel Test for Applicants v2.xlsx', sheet_name = 'Applicant Data QW')
df.columns = df.iloc[1]
df = df[2:]
df = df.dropna(axis=1,how='all')
df['Profit(Absolute)'] = df['Revenue'] - df['Expense']

df

1   ID            Campaign Revenue Expense Profit(Absolute)
2    1      Auto Insurance     441     953             -512
3    2  Mortgage Refinance     886    1138             -252
4    3      Auto Insurance     626     457              169
5    4    Health Insurance     393     763             -370
6    5    Health Insurance     825    1064             -239
7    6      Auto Insurance     336     713             -377
8    7   Purchase Mortgage     610     672              -62
9    8      Auto Insurance     678     790             -112
10   9  Mortgage Refinance     438     730             -292
11  10    Health Insurance     564     993             -429
12  11  Mortgage Refinance     703     650               53
13  12   Purchase Mortgage     959     714              245
14  13      Auto Insurance     371     782             -411
15  14      Auto Insurance     447     927             -480
16  15   Purchase Mortgage     271     686             -415
17  16    Health Insurance     965     461              504
18  17      Auto Insurance     992     307              685
19  18  Mortgage Refinance     935     526              409
20  19      Auto Insurance     624     697              -73
21  20    Health Insurance     863     745              118
22  21      Auto Insurance     829     511              318
23  22      Auto Insurance     514     913             -399
24  23    Health Insurance     517     761             -244
25  24  Mortgage Refinance     917     648              269
26  25  Mortgage Refinance     619    1070             -451
27  26  Mortgage Refinance    1060    1026               34
28  27    Health Insurance    1015     785              230
29  28  Mortgage Refinance     391     559             -168
30  29   Purchase Mortgage     279     965             -686
31  30  Mortgage Refinance     636     662              -26
32  31  Mortgage Refinance     431     585             -154
33  32    Health Insurance     363    1094             -731
34  33      Auto Insurance     381     466              -85
35  34  Mortgage Refinance     583    1087             -504
36  35      Auto Insurance     768     918             -150
37  36    Health Insurance    1136     740              396
38  37  Mortgage Refinance     417     261              156
39  38      Auto Insurance     548    1057             -509
40  39      Auto Insurance     882    1047             -165
41  40  Mortgage Refinance     809     667              142
42  41    Health Insurance    1028    1029               -1
43  42      Auto Insurance    1040     663              377
44  43      Auto Insurance     365     802             -437
45  44    Health Insurance     282    1069             -787
46  45  Mortgage Refinance     977     257              720
47  46  Mortgage Refinance     966     510              456
48  47   Purchase Mortgage    1057     278              779
49  48      Auto Insurance     851     756               95
50  49      Auto Insurance     877     865               12
51  50   Purchase Mortgage     475     919             -444

In [207]:
df.loc[df['ID']==7,'Profit(Absolute)'].values[0]

-62

In [208]:
df.loc[df['Revenue'] == df['Revenue'].max(),'ID'].values[0]

36

In [209]:
df.loc[df['Expense'] == df['Expense'].max(),'ID'].values[0]

2

In [210]:
df.loc[df['Profit(Absolute)'] == df['Profit(Absolute)'].max(),'ID'].values[0]

47

In [211]:
df['ID-Variant']= df['Campaign']+'-'+df['ID'].apply(str)
df

1,ID,Campaign,Revenue,Expense,Profit(Absolute),ID-Variant
2,1,Auto Insurance,441,953,-512,Auto Insurance-1
3,2,Mortgage Refinance,886,1138,-252,Mortgage Refinance-2
4,3,Auto Insurance,626,457,169,Auto Insurance-3
5,4,Health Insurance,393,763,-370,Health Insurance-4
6,5,Health Insurance,825,1064,-239,Health Insurance-5
7,6,Auto Insurance,336,713,-377,Auto Insurance-6
8,7,Purchase Mortgage,610,672,-62,Purchase Mortgage-7
9,8,Auto Insurance,678,790,-112,Auto Insurance-8
10,9,Mortgage Refinance,438,730,-292,Mortgage Refinance-9
11,10,Health Insurance,564,993,-429,Health Insurance-10
12,11,Mortgage Refinance,703,650,53,Mortgage Refinance-11
13,12,Purchase Mortgage,959,714,245,Purchase Mortgage-12
14,13,Auto Insurance,371,782,-411,Auto Insurance-13
15,14,Auto Insurance,447,927,-480,Auto Insurance-14
16,15,Purchase Mortgage,271,686,-415,Purchase Mortgage-15
17,16,Health Insurance,965,461,504,Health Insurance-16
18,17,Auto Insurance,992,307,685,Auto Insurance-17
19,18,Mortgage Refinance,935,526,409,Mortgage Refinance-18
20,19,Auto Insurance,624,697,-73,Auto Insurance-19
21,20,Health Insurance,863,745,118,Health Insurance-20
22,21,Auto Insurance,829,511,318,Auto Insurance-21
23,22,Auto Insurance,514,913,-399,Auto Insurance-22
24,23,Health Insurance,517,761,-244,Health Insurance-23
25,24,Mortgage Refinance,917,648,269,Mortgage Refinance-24
26,25,Mortgage Refinance,619,1070,-451,Mortgage Refinance-25
27,26,Mortgage Refinance,1060,1026,34,Mortgage Refinance-26
28,27,Health Insurance,1015,785,230,Health Insurance-27
29,28,Mortgage Refinance,391,559,-168,Mortgage Refinance-28
30,29,Purchase Mortgage,279,965,-686,Purchase Mortgage-29
31,30,Mortgage Refinance,636,662,-26,Mortgage Refinance-30
32,31,Mortgage Refinance,431,585,-154,Mortgage Refinance-31
33,32,Health Insurance,363,1094,-731,Health Insurance-32
34,33,Auto Insurance,381,466,-85,Auto Insurance-33
35,34,Mortgage Refinance,583,1087,-504,Mortgage Refinance-34
36,35,Auto Insurance,768,918,-150,Auto Insurance-35
37,36,Health Insurance,1136,740,396,Health Insurance-36
38,37,Mortgage Refinance,417,261,156,Mortgage Refinance-37
39,38,Auto Insurance,548,1057,-509,Auto Insurance-38
40,39,Auto Insurance,882,1047,-165,Auto Insurance-39
41,40,Mortgage Refinance,809,667,142,Mortgage Refinance-40
42,41,Health Insurance,1028,1029,-1,Health Insurance-41
43,42,Auto Insurance,1040,663,377,Auto Insurance-42
44,43,Auto Insurance,365,802,-437,Auto Insurance-43
45,44,Health Insurance,282,1069,-787,Health Insurance-44
46,45,Mortgage Refinance,977,257,720,Mortgage Refinance-45
47,46,Mortgage Refinance,966,510,456,Mortgage Refinance-46
48,47,Purchase Mortgage,1057,278,779,Purchase Mortgage-47
49,48,Auto Insurance,851,756,95,Auto Insurance-48
50,49,Auto Insurance,877,865,12,Auto Insurance-49
51,50,Purchase Mortgage,475,919,-444,Purchase Mortgage-50

In [212]:
df['ID-Variant'] = df['ID-Variant'].replace(' ','_',regex=True).str.lower()
df

1,ID,Campaign,Revenue,Expense,Profit(Absolute),ID-Variant
2,1,Auto Insurance,441,953,-512,auto_insurance-1
3,2,Mortgage Refinance,886,1138,-252,mortgage_refinance-2
4,3,Auto Insurance,626,457,169,auto_insurance-3
5,4,Health Insurance,393,763,-370,health_insurance-4
6,5,Health Insurance,825,1064,-239,health_insurance-5
7,6,Auto Insurance,336,713,-377,auto_insurance-6
8,7,Purchase Mortgage,610,672,-62,purchase_mortgage-7
9,8,Auto Insurance,678,790,-112,auto_insurance-8
10,9,Mortgage Refinance,438,730,-292,mortgage_refinance-9
11,10,Health Insurance,564,993,-429,health_insurance-10
12,11,Mortgage Refinance,703,650,53,mortgage_refinance-11
13,12,Purchase Mortgage,959,714,245,purchase_mortgage-12
14,13,Auto Insurance,371,782,-411,auto_insurance-13
15,14,Auto Insurance,447,927,-480,auto_insurance-14
16,15,Purchase Mortgage,271,686,-415,purchase_mortgage-15
17,16,Health Insurance,965,461,504,health_insurance-16
18,17,Auto Insurance,992,307,685,auto_insurance-17
19,18,Mortgage Refinance,935,526,409,mortgage_refinance-18
20,19,Auto Insurance,624,697,-73,auto_insurance-19
21,20,Health Insurance,863,745,118,health_insurance-20
22,21,Auto Insurance,829,511,318,auto_insurance-21
23,22,Auto Insurance,514,913,-399,auto_insurance-22
24,23,Health Insurance,517,761,-244,health_insurance-23
25,24,Mortgage Refinance,917,648,269,mortgage_refinance-24
26,25,Mortgage Refinance,619,1070,-451,mortgage_refinance-25
27,26,Mortgage Refinance,1060,1026,34,mortgage_refinance-26
28,27,Health Insurance,1015,785,230,health_insurance-27
29,28,Mortgage Refinance,391,559,-168,mortgage_refinance-28
30,29,Purchase Mortgage,279,965,-686,purchase_mortgage-29
31,30,Mortgage Refinance,636,662,-26,mortgage_refinance-30
32,31,Mortgage Refinance,431,585,-154,mortgage_refinance-31
33,32,Health Insurance,363,1094,-731,health_insurance-32
34,33,Auto Insurance,381,466,-85,auto_insurance-33
35,34,Mortgage Refinance,583,1087,-504,mortgage_refinance-34
36,35,Auto Insurance,768,918,-150,auto_insurance-35
37,36,Health Insurance,1136,740,396,health_insurance-36
38,37,Mortgage Refinance,417,261,156,mortgage_refinance-37
39,38,Auto Insurance,548,1057,-509,auto_insurance-38
40,39,Auto Insurance,882,1047,-165,auto_insurance-39
41,40,Mortgage Refinance,809,667,142,mortgage_refinance-40
42,41,Health Insurance,1028,1029,-1,health_insurance-41
43,42,Auto Insurance,1040,663,377,auto_insurance-42
44,43,Auto Insurance,365,802,-437,auto_insurance-43
45,44,Health Insurance,282,1069,-787,health_insurance-44
46,45,Mortgage Refinance,977,257,720,mortgage_refinance-45
47,46,Mortgage Refinance,966,510,456,mortgage_refinance-46
48,47,Purchase Mortgage,1057,278,779,purchase_mortgage-47
49,48,Auto Insurance,851,756,95,auto_insurance-48
50,49,Auto Insurance,877,865,12,auto_insurance-49
51,50,Purchase Mortgage,475,919,-444,purchase_mortgage-50

In [213]:
df.loc[df['Revenue'] == df['Revenue'].max(),'ID-Variant'].values[0]

'health_insurance-36'

In [214]:
df.loc[df['Expense'] == df['Expense'].max(),'ID-Variant'].values[0]

'mortgage_refinance-2'

In [215]:
df.loc[df['Profit(Absolute)'] == df['Profit(Absolute)'].max(),'ID-Variant'].values[0]

'purchase_mortgage-47'

In [219]:
df2 = df.groupby(df['Campaign']).sum()

In [220]:
df2 = df2.drop(['ID','ID-Variant','Campaign'],axis=1)

KeyError: "['Campaign'] not found in axis"

In [218]:
df2

1,Campaign,Revenue,Expense,Profit(Absolute)
Campaign,,,,
Auto Insurance,Auto InsuranceAuto InsuranceAuto InsuranceAuto...,11570,13624,-2054
Health Insurance,Health InsuranceHealth InsuranceHealth Insuran...,7951,9504,-1553
Mortgage Refinance,Mortgage RefinanceMortgage RefinanceMortgage R...,10768,10376,392
Purchase Mortgage,Purchase MortgagePurchase MortgagePurchase Mor...,3651,4234,-583

In [221]:
df2.reset_index(inplace = True)

In [222]:
df2

1,Campaign,ID,Revenue,Expense,Profit(Absolute),ID-Variant
0,Auto Insurance,451,11570,13624,-2054,auto_insurance-1auto_insurance-3auto_insurance...
1,Health Insurance,258,7951,9504,-1553,health_insurance-4health_insurance-5health_ins...
2,Mortgage Refinance,406,10768,10376,392,mortgage_refinance-2mortgage_refinance-9mortga...
3,Purchase Mortgage,160,3651,4234,-583,purchase_mortgage-7purchase_mortgage-12purchas...

In [225]:
df2 = df2.drop(['ID','ID-Variant'],axis=1)

In [226]:
df2['Profit Margin %'] = df2['Profit(Absolute)'] / df2['Revenue']
format_dict = {'Profit Margin %': '{:.2%}'}
df3 = df2.style.format(format_dict)
df3

In [227]:
df2.loc[df2['Profit Margin %'] == df2['Profit Margin %'].max(),'Campaign'].values[0]

'Mortgage Refinance'

In [228]:
df2.loc[df2['Profit(Absolute)'] == df2['Profit(Absolute)'].max(),'Campaign'].values[0]

'Mortgage Refinance'

In [230]:
with pd.ExcelWriter('QW Answer.xlsx') as writer:
    df.to_excel(writer, sheet_name = 'Applicant Data QW')
    df3.to_excel(writer, sheet_name = 'Campaign Summary QW')